Feature/relations
bildvitta/navpi pull request #6
Opened 2020-11-09 18:46 UTC by DouglasCalora

2020-11-10 23:29 UTC, caiotarifa requested changes

2020-11-10 23:29 UTC, caiotarifa commented on src/utils/relations.js
> +  return uuid ? { uuid } : uuid
Faz sentido isso mesmo? Se não tem `uuid` retorna `uuid`?

2020-11-10 23:29 UTC, caiotarifa commented on src/utils/models.js
> +    : extension === 'js' ? require(path) : filesystem.read(path, 'json')
Por que tirou a identação?

2020-11-10 23:29 UTC, caiotarifa commented on src/utils/formatResponse.js
> +}
Achei o código um pouquinho verboso (não é problema de lógica).

Uma sugestão.

```
for (const key in result) {
  const fieldsKey = relationFields[key]
  const resultKey = result[key]

  if (fieldsKey && resultKey) {
    result[key] = fieldsKey.type === 'select' && !fieldsKey.multiple
      ? resultKey.uuid
      : resultKey.map(item => item.uuid)
  }
}
```

2020-11-10 23:29 UTC, caiotarifa commented on src/utils/formatResponse.js
> +  })
```
return options.map(option => ({
  label: option[model],
  value: option['uuid']
}))
```

2020-11-10 23:29 UTC, caiotarifa commented on src/commands/seed.js
> +            : fields[key].__value || seederTypes[fields[key].type]
Como isso funciona? Qual a lógica aqui? Pode me dar mais informações? Fiquei confuso.

Isso está documentado?

2020-11-11 12:51 UTC, DouglasCalora commented on src/commands/seed.js
> +        throw new Error(error)
Não consegui simular o erro, removido.

2020-11-11 13:24 UTC, DouglasCalora commented on src/utils/relations.js
> +          ]
tem casos que ele pode vir undefined e da erro.

2020-11-11 13:24 UTC, DouglasCalora commented on src/utils/relations.js
> +        ]
tem casos que ele pode vir undefined e da erro.

2020-11-11 13:30 UTC, DouglasCalora commented on src/utils/relations.js
> +  return uuid ? { uuid } : uuid
mudado para `null`

2020-11-11 13:30 UTC, DouglasCalora commented on src/utils/models.js
> +    : extension === 'js' ? require(path) : filesystem.read(path, 'json')
do outro jeito estava meio confuso, e ai cabe em uma linha

2020-11-11 13:37 UTC, DouglasCalora commented on src/utils/formatResponse.js
> +}
feito

2020-11-11 13:38 UTC, DouglasCalora commented on src/utils/formatResponse.js
> +  })
feito

2020-11-11 13:39 UTC, DouglasCalora commented on src/commands/seed.js
> +            : fields[key].__value || seederTypes[fields[key].type]
Explicado no wpp

2020-11-11 13:42 UTC, DouglasCalora commented on src/utils/relations.js
> +  return list.map(item => { return { uuid: item } })
Feito

2020-11-11 13:51 UTC, DouglasCalora commented on src/utils/relations.js
> +        const isMultiple = relations[key][relationKey].multiple
Feito

2020-11-12 02:33 UTC, caiotarifa approved these changes

2020-11-12 02:33 UTC, caiotarifa commented on src/commands/seed.js
> +            : fields[key].__value || seederTypes[fields[key].type]
Doug, você me explicou o que e não como ou a lógica.

2020-11-12 02:33 UTC, caiotarifa commented on src/utils/models.js
> +    : extension === 'js' ? require(path) : filesystem.read(path, 'json')
Mas o correto pelo Standard é com indentação.

<img width="527" alt="Captura de Tela 2020-11-11 às 23 27 40" src="https://user-images.githubusercontent.com/197979/98887868-7fde9800-2475-11eb-9e12-a2d95526c601.png">

2020-11-12 16:25 UTC, merged